### ISSUE TITLE
Support for local attention

### ISSUE THREAD

**Issue by tkon3** [lucidrains/x-transformers#110]
Hi, 

I'm currently working on long sequences.
Not sure if someone asked this before but is support for local attention planned ?
ALiBi is inefficient because it keeps the O(n^2) complexity.

I found an implementation of block local attention if needed:
https://github.com/ccdv-ai/convert_checkpoint_to_lsg/tree/main/block_local_attention

Thank you

**Comment by lucidrains** [comment]
@tkon3 i recommend https://github.com/lucidrains/local-attention , but it doesn't have the full transformer and all the other features

**Comment by lucidrains** [comment]
@tkon3 there's another option i'd recommend, which is to use [flash attention](https://github.com/HazyResearch/flash-attention)

**Comment by lucidrains** [comment]
@tkon3 ohh shoot, yeah that may be too long, even for flash attention haha

local attention is your best bet! maybe i'll build out a full transformer there with some of the features that actually work

**Comment by platers** [comment]
Im also interested in local attention, would it be difficult to add? If not I may take a shot at it.

**Comment by lucidrains** [comment]
@platers hey Victor, i feel like it is a bit out of scope for this repo

what would you need in the [local-attention](https://github.com/lucidrains/local-attention) for it to be usable?

**Comment by lucidrains** [comment]
@platers what kind of context lengths are you working with? is flash attention not sufficient?

**Comment by lucidrains** [comment]
@platers the other issue is that local can mean many different things depending on what you are working with

not to mention variations like shifted windows etc

**Comment by lucidrains** [comment]
here's another alternative https://github.com/lucidrains/FLASH-pytorch

**Comment by platers** [comment]
@lucidrains Thanks for the response! I'm interested in context lengths of around 15k. I'm training on poorly aligned audio data, so feeding in the whole file would save me a lot of alignment work. I think local attention is enough because my targets should be temporally close to the input. I've since found a way to align the data, so this isnt critical to me anymore, but it would be nice. 

An example of a simple transformer implementation like gpt or T5 in local-attention would convince me to use it. I don't need the bells and whistles in this repo, just a minimal example.

**Comment by lucidrains** [comment]
@platers let me know if https://github.com/lucidrains/local-attention#local-attention-transformer helps

**Comment by lucidrains** [comment]
closing since it is working for me (and incorporated into audiolm)
