### ISSUE TITLE
How to make inference fast (by adding caching of key / values)

### ISSUE THREAD

**Issue by PhenomenalOnee** [lucidrains/x-transformers#29]
How can we implement the below caching technique in the code?

That would be awesome. 
What I have tried to speed up the inference in my custom implementations for autoregressive self-attention is caching the output of the self-attention at timestep T and then, in timestep T+1, passing the full keys/values but only passing the last element of the query sequence, then getting the output and concatenating it with the cache, that way each query can pay attention to the full previous sequence but we don't need to compute attention for all the previous queries when we only need the output at T+1
 It looks something like this:
<img width="931" alt="Captura de pantalla 2021-03-12 a las 17 01 32" src="https://user-images.githubusercontent.com/4237014/110965568-9aa61800-8354-11eb-8065-838175be8dc0.png">
But I only achieved a x3 speedup 🤔 

I actually needed to perform autoregressive inference in a very large dataset, and it was taking more than 1 day even with the above speedup. I am currently doing some weird custom stuff, keeping the Transformer attention layers but replacing the self-attention layers with LSTMs, which are way faster at generating sequences token by token, and with that I achieve the x10 speedup that I needed.

_Originally posted by @pabloppp in https://github.com/lucidrains/x-transformers/issues/21#issuecomment-797589687_

**Comment by pabloppp** [comment]
Well, I did mine in a custom Transformer implementation, what I basically did is the following:

The attention layers generally receive Q, K & V and output a sequence, I added an extra input called cache.
Then inside the attention layer, for Q I only took the element at the last position in the sequence:
```
q = q[-1:]
```
Then I applied regular attention to the new Q with the regular K & V, but the problem now is that your output sequence has length 1 because you only took your last Q, so here is where the cache comes to play, you will concatenate the cache to your output:
```
output = torch.cat([cache, output], dim=1)
```
and then you will keep your output as the cache for the next element in the sequence, so the final look of the attention layer would be:
```
output_t0 = attention(q_t0, k_t0, v_t0)
...
output_t1 = attention(q_t0, k_t0, v_t0, cache = output_t0)
```

**Comment by BitCalSaul** [comment]
@PhenomenalOnee Before I thought the PyTorch would automatically do self attention between the new token with previous tokens in the decoder, and cross attention between the new token with the tokens from encoder.  But the fact is that the when every new token comes in, the previous tokens would do cross attention again to get the same outputs for themselves. I don't know if I understand right but if it's the truth, the efficiency would be much low.

**Comment by lucidrains** [comment]
turns out you can actually go a bit faster https://crfm.stanford.edu/2023/10/12/flashdecoding.html but it requires that you are one of the CUDA experts out there

**Comment by lucidrains** [comment]
anyways, closing this as caching of key/values have been implemented!
